### ISSUE TITLE
IOS 8 return success even with invalid certificate

### ISSUE THREAD

**Issue by bhrott** [EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin#21]
Hi,

I try to validate certificate using iis dev certificate (expecting error callback) and a expired certificate. 
In Android it works fine, but on ios 8 the success callback is raised on every request.
- IOS 8.1
- Phonegap build

Some help?

Thanks.

**Comment by dfilip** [comment]
I'm having this issue as well in iOS9. I take the valid fingerprint, modify several characters, and it returns success. Cordova/Ionic.

**Comment by TheDauntless** [comment]
@dfilip can you provide a proof of concept that would show this vulnerability?

**Comment by EddyVerbruggen** [comment]
@dfilip That can happen if you first check against a valid fp and within a minute or so with an invalid fp. That's because iOS caches the server response for a little while. If you always check only with the valid fp you're good. If the server changes in the meanwhile (due to a MitM attack or something else) I don't think you'll get a cached response, so the fp will be evaluated.

**Comment by Sumitmadan22dec** [comment]
Hi I'm facing this issue again every time I got success message no matters what certificate I'm using and I'm using the latest version of this plugin in my Cordova IOS App. Pl. let me know if I miss something to Add anything in config.xml file so that plugin can work properly. For information it works perfectly on Android platform.
[https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin](https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin)
